# 查看生效的自动配置类
debug: false

spring:
  profiles:
    active: demo
#  DB
  datasource:
    username: root
    password: Nanaan7an
#    链接数据库地址，3306为默认端口；时区报错一般加时区
    url: jdbc:mysql://localhost:3306/try2pay?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    指定数据源，可配置相关的Druid特有配置；这些配置默认不注入，需要开发者手动绑定，见DruidConfig
#    type: Druid

#Redis
  redis:
    host: 121.40.172.13
    port: 6379
    password: Admin@123
    database: 0
server:
  port: 8080

#日志级别
logging:
  level:
    com.example.demo: debug
#---
#spring:
#  profiles: demo
#server:
#  port: 8081
#
#pay-in-yml:
#  payId: pay${random.uuid}


mybatis:
  #classpath表示resources/目录，且:之后没有/
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.pojo
